=== ydubey/blog/spring-boot-jpa-yaml-swagger-cucumber-profiles-sample/src/test/resources/schema/user.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": ["id", "name", "date_of_birth", "authorities"],
  "properties": {
    "id": {"type": "integer"},
    "name": {"type": "string"},
    "date_of_birth": {
      "type": "string",
      "pattern": "^(19|20)\\d\\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$"
    },
    "authorities": {"$ref": "authorities.json"}
  },
  "additionalProperties": false
}

=== ydubey/blog/spring-boot-jpa-yaml-swagger-cucumber-profiles-sample/src/test/resources/json/users.json
[
  {
    "id": 1,
    "name": "admin",
    "authorities": [
      {
        "id": 1,
        "name": "ROLE_ADMIN"
      },
      {
        "id": 3,
        "name": "ROLE_USER"
      }
    ],
    "date_of_birth": "1983-07-11"
  },
  {
    "id": 2,
    "name": "guest",
    "authorities": [
      {
        "id": 2,
        "name": "ROLE_GUEST"
      }
    ],
    "date_of_birth": "1969-10-12"
  },
  {
    "id": 3,
    "name": "user",
    "authorities": [
      {
        "id": 3,
        "name": "ROLE_USER"
      }
    ],
    "date_of_birth": "1996-02-13"
  }
]
